# 线上配置文件

server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1Panel-mysql-V7XN:3306/leaves_word
    username: leaves_word
    password: PDYQAz4tFJQxCJDt
  redis:
    database: 1
    host: 1Panel-redis-UrmH
    port: 6379
    timeout: 5000
    password: yXaS2jXz3Xz7BEHb
  # Elasticsearch 配置
  # todo 需替换配置
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: PDYQAz4tFJQxCJDt
